### ISSUE TITLE
Certificate issues

### ISSUE THREAD

**Issue by agsola** [tomwalder/php-gds#140]
I'm getting certificate issues in some of the queries.
Any ideas?

Maybe should be nice a way to disable certificate check to avoid having errores with cURL.

I get this error:
Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 51: SSL peer certificate or SSH remote key was not OK (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /ROUTE/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
Stack trace:
#0 /ROUTE/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /ROUTE/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /ROUTE/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handle

**Comment by tomwalder** [comment]
My guess is that your local CA file is out of date.

I have not had any issues like this.

**Comment by agsola** [comment]
Most of the queries are done properly without issues. But I've added a catch to get the errors and mail me and I've noticed that.

**Comment by kafcom** [comment]
Just so you know what worked for me, The file in the zip folder in the post at ([Post on solving this issue](http://flwebsites.biz/posts/how-fix-curl-error-60-ssl-issue)) worked for me with no issues at all.

Copy the certificate file to a location on your hard drive, update the line

`;curl.cainfo `

in your php.ini file to read

`curl.cainfo= "path_to_cert\cacert.pem"`

Restart your Apache server. You should be fine.

By the way, Awesome work Tom. You are a life saver.

**Comment by agsola** [comment]
Thank you kafcom, though it seems weird to me, since if that were the problem I always would get that problem. Maybe is when trying to get an intermediate CA...
