### ISSUE TITLE
Class 'GuzzleHttp\HandlerStack' not found in /src/GDS/Gateway/RESTv1.php:92

### ISSUE THREAD

**Issue by shahariaazam** [tomwalder/php-gds#154]
```php
Error: Class 'GuzzleHttp\HandlerStack' not found in ....../vendor/tomwalder/php-gds/src/GDS/Gateway/RESTv1.php:92
Stack trace:
#0 ....../vendor/tomwalder/php-gds/src/GDS/Gateway/RESTv1.php(78): GDS\Gateway\RESTv1->initHttpClient()
#1 ......./vendor/tomwalder/php-gds/src/GDS/Gateway/RESTv1.php(154): GDS\Gateway\RESTv1->httpClient()
```

This library is using `GuzzleHttp\HandlerStack ` that is coming from GuzzleHttp package. But this dependency is not declared in `composer.json`. Does it make any sense? Is it considering Guzzle as default http client? Can anybody explain?

**Comment by tomwalder** [comment]
Sorry for the late reply. Are you still having this issue?

I suspect it's a dependancy issue at your end?
