### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by shashankta** [tomwalder/php-gds#158]
Can you please help me on this.Not able connect and run query

PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/datastore/v1beta2/datasets/tringappsblog/runQuery: (404) Not Found' in /base/data/home/apps/s~fronttringapp/v1.402009994233015606/vendor/google/apiclient/src/Google/Http/REST.php:110
Stack trace:
#0 /base/data/home/apps/s~fronttringapp/v1.402009994233015606/vendor/google/apiclient/src/Google/Http/REST.php(62): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#2 /base/data/home/apps/s~fronttringapp/v1.402009994233015606/vendor/google/apiclient/src/Google/Task/Runner.php(174): call_user_func_array(Array, Array)
#3 /base/data/home/apps/s~fronttringapp/v1.402009994233015606/vendor/google/apiclient/src/Google/Http/REST.php(46): Google_Task_Runner->run()
#4 /base/data/home/apps/s~fronttringapp/v1.402009994233015606/vendor/google/apiclient/src/Google/Client.php(590): Goo in /base/data/home/apps/s~fronttringapp/v1.402009994233015606/vendor/google/apiclient/src/Google/Http/REST.php on line 110

**Comment by tomwalder** [comment]
Hi. This looks like you might be using an old version of the REST client (v1beta2 in your URL).

Are you using the latest version?

**Comment by shashankta** [comment]
Can you please tell me whats the new url of REST client.
